name: data_service
description: "Provides CRUD operations of the Eterna mobile application."
version: 1.0.0

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3

flutter:
